"""empty message

Revision ID: cf412a4506f2
Revises: 938901e79aef
Create Date: 2017-10-22 20:17:00.771532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf412a4506f2'
down_revision = '938901e79aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computer')
    op.add_column('ad', sa.Column('cylinder', sa.String(), nullable=True))
    op.add_column('ad', sa.Column('drive', sa.String(), nullable=True))
    op.add_column('ad', sa.Column('fuel', sa.String(), nullable=True))
    op.add_column('ad', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ad', 'person', ['person_id'], ['id'])
    op.drop_column('ad', 'subtitle')
    op.drop_column('ad', 'condition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('condition', postgresql.ENUM('occasion', 'new', name='conditionenum'), autoincrement=False, nullable=True))
    op.add_column('ad', sa.Column('subtitle', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ad', type_='foreignkey')
    op.drop_column('ad', 'person_id')
    op.drop_column('ad', 'fuel')
    op.drop_column('ad', 'drive')
    op.drop_column('ad', 'cylinder')
    op.create_table('computer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('serial', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='computer_person_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='computer_pkey')
    )
    # ### end Alembic commands ###
